
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Podium.Application.DTOs.Video;
using Podium.Application.Interfaces;
using Podium.Core.Constants;
using Podium.Core.Entities;
using Podium.Core.Interfaces;
using Podium.Infrastructure.Data;
using Video = Podium.Core.Entities.Video;
using Microsoft.Extensions.Configuration;

namespace Podium.Application.Services
{
    public class VideoService : IVideoService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IVideoStorageService _storageService;
        private readonly ILogger<VideoService> _logger;
        private readonly IConfiguration _configuration;

        public VideoService(
            IUnitOfWork unitOfWork,
            IVideoStorageService storageService,
            ILogger<VideoService> logger,
            IConfiguration configuration)
        {
            _unitOfWork = unitOfWork;
            _storageService = storageService;
            _logger = logger;
            _configuration = configuration;
        }

        public async Task<List<MyVideoListItem>> GetMyVideosAsync(int studentId)
        {
            var videos = await _unitOfWork.Videos.FindAsync(v => v.StudentId == studentId);

            // Map to DTO
            return videos.Select(v => new MyVideoListItem
            {
                VideoId = v.Id,
                Title = v.Title,
                ThumbnailUrl = v.ThumbnailUrl,
                UploadedDate = v.CreatedAt,
                ViewCount = v.ViewCount,
                IsReviewed = v.IsReviewed
                // Map status to DTO if needed
            }).ToList();
        }

        public async Task<VideoResponse> GetVideoDetailsAsync(int videoId, int? currentUserId, string userRole)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) throw new KeyNotFoundException("Video not found");

            // Security check: Ensure student owns video or user is staff
            // (You might move this logic to a PermissionService later)
            if (userRole == Roles.Student && video.StudentId != currentUserId)
            {
                throw new UnauthorizedAccessException("Cannot view this video.");
            }

            // Only generate URL if video is Ready
            string videoUrl = string.Empty;
            if (video.Status == VideoStatus.Ready)
            {
                videoUrl = await _storageService.GetVideoUrlAsync(video.Url);
            }

            var response = new VideoResponse
            {
                VideoId = video.Id,
                Title = video.Title,
                Description = video.Description,
                Instrument = video.Instrument,
                VideoUrl = videoUrl,
                UploadedDate = video.CreatedAt
            };

            return response;
        }

        public async Task<(bool success, string message)> ValidateVideoUploadAsync(int studentId, long fileSizeBytes)
        {
            // Retrieve max size from config, default to 500 if missing (or throw if you prefer strict)
            int maxFileSizeMB = _configuration.GetValue<int>("Video:MaxFileSizeMB");

            // If the config value is 0 (missing), you might want to handle it. 
            // Here we assume it's set correctly in appsettings.
            if (maxFileSizeMB == 0) maxFileSizeMB = 500;

            long maxFileSizeBytes = maxFileSizeMB * 1024L * 1024L;

            if (fileSizeBytes > maxFileSizeBytes)
            {
                return (false, $"File size exceeds {maxFileSizeMB}MB limit.");
            }

            return (true, "Upload approved");
        }

        public async Task<Video> CreateVideoAsync(int studentId, CreateVideoRequest request)
        {
            // 1. Generate a unique filename for cloud storage
            var fileName = $"{studentId}/{Guid.NewGuid()}_{request.FileName}";

            // 2. Create the DB Entity first (or you can do it after upload confirmation)
            var video = new Video
            {
                StudentId = studentId,
                Title = request.Title,
                Description = request.Description,
                Instrument = request.Instrument,
                Url = fileName, // Store the path, not the full URL
                IsPublic = request.IsPublic,
                CreatedAt = DateTime.UtcNow,
                Status = VideoStatus.Uploading,

                ViewCount = 0,
                IsReviewed = false
            };

            await _unitOfWork.Videos.AddAsync(video);
            await _unitOfWork.SaveChangesAsync();

            // Note: The actual file upload happens on the frontend using the 
            // URL generated by the StorageService, typically returned in a separate step 
            // or as part of this response.
            return video;
        }

        public async Task<VideoRatingResponse> RateVideoAsync(int videoId, int recruiterId, RateVideoRequest request)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) throw new KeyNotFoundException("Video not found");

            // Check if rating already exists
            // (Assuming you add a VideoRatings repository to UnitOfWork)
            var existingRating = await _unitOfWork.VideoRatings.FirstOrDefaultAsync(r =>
                r.VideoId == videoId && r.BandStaffId == recruiterId);

            if (existingRating != null)
            {
                // Update existing
                existingRating.Rating = request.Rating;
                existingRating.Comment = request.Comment;
                existingRating.UpdatedAt = DateTime.UtcNow;
                _unitOfWork.VideoRatings.Update(existingRating);
            }
            else
            {
                // Create new
                var rating = new VideoRating
                {
                    VideoId = videoId,
                    BandStaffId = recruiterId,
                    Rating = request.Rating,
                    Comment = request.Comment,
                    CreatedAt = DateTime.UtcNow
                };
                await _unitOfWork.VideoRatings.AddAsync(rating);
            }

            // Mark video as reviewed if it wasn't before
            if (!video.IsReviewed)
            {
                video.IsReviewed = true;
                _unitOfWork.Videos.Update(video);
            }

            await _unitOfWork.SaveChangesAsync();

            return new VideoRatingResponse
            {
                Success = true,
                Message = "Rating submitted"
            };
        }

        // Implement remaining methods (UpdateVideo, SoftDelete, etc.) similarly...
        public async Task<List<VideoRatingResponse>> GetVideoRatingsAsync(int videoId)
        {
            // Verify video exists
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) throw new KeyNotFoundException("Video not found");

            // Use GetQueryable to Include related BandStaff data for the rater's name
            var ratings = await _unitOfWork.VideoRatings.GetQueryable()
                .Where(r => r.VideoId == videoId)
                .Include(r => r.BandStaff)
                .OrderByDescending(r => r.CreatedAt)
                .ToListAsync();

            return ratings.Select(r => new VideoRatingResponse
            {
                RatingId = r.Id,
                BandStaffName = r.BandStaff != null ? $"{r.BandStaff.FirstName} {r.BandStaff.LastName}" : "Unknown Staff",
                Rating = r.Rating,
                Comment = r.Comment,
                CreatedAt = r.CreatedAt,
                Success = true
            }).ToList();
        }

        public async Task<Video> UpdateVideoAsync(int videoId, int studentId, UpdateVideoRequest request)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);

            if (video == null)
                throw new KeyNotFoundException($"Video {videoId} not found");

            // Authorization: Ensure the student owns this video
            if (video.StudentId != studentId)
                throw new UnauthorizedAccessException("You do not have permission to update this video.");

            // Update Fields
            video.Title = request.Title;
            video.Description = request.Description;
            video.IsPublic = request.IsPublic;

            // Allow updating thumbnail if provided (optional)
            // if (!string.IsNullOrEmpty(request.ThumbnailUrl)) video.ThumbnailUrl = request.ThumbnailUrl;

            _unitOfWork.Videos.Update(video);
            await _unitOfWork.SaveChangesAsync();

            return video;
        }

        public async Task<bool> SoftDeleteVideoAsync(int videoId, int studentId)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);

            if (video == null) return false;

            // Authorization: Ensure the student owns this video
            if (video.StudentId != studentId)
                throw new UnauthorizedAccessException("You do not have permission to delete this video.");

            // Use the Repository's Remove method which now handles Soft Delete 
            // (based on your ISoftDelete implementation in the repository)
            _unitOfWork.Videos.Remove(video);

            await _unitOfWork.SaveChangesAsync();
            return true;
        }

        public async Task<bool> IncrementViewCountAsync(int videoId)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) return false;

            video.ViewCount++;
            _unitOfWork.Videos.Update(video);
            await _unitOfWork.SaveChangesAsync();
            return true;
        }

        public async Task<ServiceResult<PagedResult<VideoThumbnailDto>>> GetStudentVideoThumbnailsAsync(int studentId, int page, int pageSize)
        {
            // Security: Ensure the student exists (optional, could be handled by caller)
            if (!await _unitOfWork.Students.AnyAsync(s => s.Id == studentId && !s.IsDeleted))
                return ServiceResult<PagedResult<VideoThumbnailDto>>.Failure("Student not found");

            var result = await _unitOfWork.Videos.GetPagedProjectionAsync(
                predicate: v => v.StudentId == studentId && !v.IsDeleted,
                selector: v => new VideoThumbnailDto
                {
                    Id = v.Id,
                    Title = v.Title,
                    ThumbnailUrl = v.ThumbnailUrl ?? "",
                    Url = v.Url,
                    IsPrimary = v.IsPrimary,
                    Instrument = v.Instrument,
                    ViewCount = v.ViewCount,
                    Status = v.Status.ToString()
                },
                page: page,
                pageSize: pageSize,
                orderBy: v => v.CompletedAt // Sort by newest
            );

            // Correct descending order for dates usually requires OrderByDescending 
            // The Repository's generic helper currently takes OrderBy (ascending). 
            // If strict sorting is needed, the Repository helper might need an update or we sort in memory for small pages.
            // For now, we assume the repository method handles the Expression passed to it (which defaults to ascending).

            return ServiceResult<PagedResult<VideoThumbnailDto>>.Success(result);
        }

        public Task<VideoRatingResponse> UpdateRatingAsync(int videoId, int recruiterId, RateVideoRequest request)
        {
            // Reuse logic from RateVideoAsync or implement specific update logic
            return RateVideoAsync(videoId, recruiterId, request);
        }

        public async Task<bool> UpdateTranscodingStatusAsync(string uploadId, TranscodingWebhookRequest request)
        {
            // Assuming uploadId corresponds to the stored Url path (e.g. "{studentId}/{guid}_{filename}")
            // or we use a dedicated JobId field. For now, we look up by Url.
            var video = await _unitOfWork.Videos.FirstOrDefaultAsync(v => v.Url == uploadId);

            if (video == null)
            {
                _logger.LogWarning($"Transcoding webhook received for unknown video: {uploadId}");
                return false;
            }

            _logger.LogInformation($"Updating transcoding status for video {video.Id} to {request.Status}");

            // Map Webhook Status to Enum
            switch (request.Status?.ToLower())
            {
                case "processing":
                    video.Status = VideoStatus.Processing;
                    break;
                case "completed":
                case "finished":
                case "ready":
                    video.Status = VideoStatus.Ready;
                    video.CompletedAt = DateTime.UtcNow;
                    if (!string.IsNullOrEmpty(request.ThumbnailPath))
                    {
                        video.ThumbnailUrl = request.ThumbnailPath;
                    }
                    if (!string.IsNullOrEmpty(request.OutputUrl))
                    {
                        // Optionally update URL if the transcoded output location differs
                        // video.Url = request.OutputUrl; 
                    }
                    break;
                case "failed":
                case "error":
                    video.Status = VideoStatus.Failed;
                    video.TranscodingError = request.ErrorMessage;
                    break;
                default:
                    // Log unknown status but don't fail
                    _logger.LogWarning($"Unknown transcoding status: {request.Status}");
                    break;
            }

            // Update legacy string field if needed
            video.TranscodingStatus = request.Status;

            _unitOfWork.Videos.Update(video);
            await _unitOfWork.SaveChangesAsync();

            return true;
        }
    }
}