
using Microsoft.Extensions.Logging;
using Podium.Application.DTOs.Video;
using Podium.Application.Interfaces;
using Podium.Core.Entities;
using Podium.Core.Interfaces;
using Video = Podium.Core.Entities.Video; // Assuming generic interfaces live here

namespace Podium.Application.Services
{
    public class VideoService : IVideoService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IVideoStorageService _storageService;
        private readonly ILogger<VideoService> _logger;

        public VideoService(
            IUnitOfWork unitOfWork,
            IVideoStorageService storageService,
            ILogger<VideoService> logger)
        {
            _unitOfWork = unitOfWork;
            _storageService = storageService;
            _logger = logger;
        }

        public async Task<List<MyVideoListItem>> GetMyVideosAsync(int studentId)
        {
            var videos = await _unitOfWork.Videos.FindAsync(v => v.StudentId == studentId);

            // Map to DTO
            return videos.Select(v => new MyVideoListItem
            {
                VideoId = v.Id,
                Title = v.Title,
                ThumbnailUrl = v.ThumbnailUrl,
                UploadedDate = v.CreatedAt,
                ViewCount = v.ViewCount,
                IsReviewed = v.IsReviewed
            }).ToList();
        }

        public async Task<VideoResponse> GetVideoDetailsAsync(int videoId, int? currentUserId, string userRole)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) throw new KeyNotFoundException("Video not found");

            // Security check: Ensure student owns video or user is staff
            // (You might move this logic to a PermissionService later)
            if (userRole == "Student" && video.StudentId != currentUserId)
            {
                throw new UnauthorizedAccessException("Cannot view this video.");
            }

            var response = new VideoResponse
            {
                VideoId = video.Id,
                Title = video.Title,
                Description = video.Description,
                Instrument = video.Instrument,
                VideoUrl = await _storageService.GetVideoUrlAsync(video.Url), // Generate signed URL
                UploadedDate = video.CreatedAt
            };

            return response;
        }

        public async Task<(bool success, string message)> ValidateVideoUploadAsync(int studentId, long fileSizeBytes)
        {
            // 1. Check storage quotas (optional)
            // 2. Check max file size (e.g., 500MB)
            const long maxFileSize = 500 * 1024 * 1024;
            if (fileSizeBytes > maxFileSize)
            {
                return (false, "File size exceeds 500MB limit.");
            }

            return (true, "Upload approved");
        }

        public async Task<Video> CreateVideoAsync(int studentId, CreateVideoRequest request)
        {
            // 1. Generate a unique filename for cloud storage
            var fileName = $"{studentId}/{Guid.NewGuid()}_{request.FileName}";

            // 2. Create the DB Entity first (or you can do it after upload confirmation)
            var video = new Video
            {
                StudentId = studentId,
                Title = request.Title,
                Description = request.Description,
                Instrument = request.Instrument,
                Url = fileName, // Store the path, not the full URL
                IsPublic = request.IsPublic,
                CreatedAt = DateTime.UtcNow
            };

            await _unitOfWork.Videos.AddAsync(video);
            await _unitOfWork.SaveChangesAsync();

            // Note: The actual file upload happens on the frontend using the 
            // URL generated by the StorageService, typically returned in a separate step 
            // or as part of this response.
            return video;
        }

        public async Task<VideoRatingResponse> RateVideoAsync(int videoId, int recruiterId, RateVideoRequest request)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) throw new KeyNotFoundException("Video not found");

            // Check if rating already exists
            // (Assuming you add a VideoRatings repository to UnitOfWork)
            var existingRating = await _unitOfWork.VideoRatings.FirstOrDefaultAsync(r =>
                r.VideoId == videoId && r.BandStaffId == recruiterId);

            if (existingRating != null)
            {
                // Update existing
                existingRating.Rating = request.Rating;
                existingRating.Comment = request.Comment;
                existingRating.UpdatedAt = DateTime.UtcNow;
                _unitOfWork.VideoRatings.Update(existingRating);
            }
            else
            {
                // Create new
                var rating = new VideoRating
                {
                    VideoId = videoId,
                    BandStaffId = recruiterId,
                    Rating = request.Rating,
                    Comment = request.Comment,
                    CreatedAt = DateTime.UtcNow
                };
                await _unitOfWork.VideoRatings.AddAsync(rating);
            }

            // Mark video as reviewed if it wasn't before
            if (!video.IsReviewed)
            {
                video.IsReviewed = true;
                _unitOfWork.Videos.Update(video);
            }

            await _unitOfWork.SaveChangesAsync();

            return new VideoRatingResponse
            {
                Success = true,
                Message = "Rating submitted"
            };
        }

        // Implement remaining methods (UpdateVideo, SoftDelete, etc.) similarly...

        public Task<Video> UpdateVideoAsync(int videoId, int studentId, UpdateVideoRequest request)
        {
            throw new NotImplementedException();
        }

        public Task<bool> SoftDeleteVideoAsync(int videoId, int studentId)
        {
            throw new NotImplementedException();
        }

        public async Task<bool> IncrementViewCountAsync(int videoId)
        {
            var video = await _unitOfWork.Videos.GetByIdAsync(videoId);
            if (video == null) return false;

            video.ViewCount++;
            await _unitOfWork.SaveChangesAsync();
            return true;
        }

        public Task<List<VideoRatingResponse>> GetVideoRatingsAsync(int videoId)
        {
            throw new NotImplementedException();
        }

        public Task<VideoRatingResponse> UpdateRatingAsync(int videoId, int recruiterId, RateVideoRequest request)
        {
            // Reuse logic from RateVideoAsync or implement specific update logic
            return RateVideoAsync(videoId, recruiterId, request);
        }

        public Task<bool> UpdateTranscodingStatusAsync(string uploadId, TranscodingWebhookRequest request)
        {
            // Logic to handle callbacks from Azure Media Services or AWS MediaConvert
            return Task.FromResult(true);
        }
    }
}